### ISSUE TITLE
Shumway could not be verified for use in Firefox (FF43.0)

### ISSUE THREAD

**Issue by CWood1** [mozilla/shumway#2405]
![screenshot_2015-12-20_13-07-23](https://cloud.githubusercontent.com/assets/1674890/11918090/b7940ed4-a71a-11e5-8edf-fd5beccf2b36.png)
Recently upgraded to Firefox 43.0, and got the above error. I had to disable xpinstall.signatures.required in order to re-enable the player.

**Comment by Transiberian** [comment]
same for me ...

**Comment by Mitchykins** [comment]
I have the same issue.

I don't get it, isn't this by Mozilla themselves?

**Comment by yurydelendik** [comment]
Fixed by 1a32b7365f65a5c69f849d33163fc97bbc371cdd and c219d3beaa440028beececc1c6ab9a08440bdbf0.

Also somebody already submitted addon with the same id to AMO -- I had to change ID to shumway-dev@research.mozilla.org

There was also problem with time (the time on botio server was off by few minutes) and AMO has issue with that. Closing as fixed.
